version: "3.7"
services:
  db:
    image: mongo
    restart: always
    networks:
      - default
    ports:
      - "27017:27017"
    container_name: mongodb

  api:
    build: .
    ports:
      - "4444:4444"
    depends_on:
      - db
